// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import TestController from "./test_controller";
application.register("test", TestController);

import CsvUploadController from "./csv_upload_controller";
application.register("csv-upload", CsvUploadController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);

import DropdownController from "./dropdown_controller";
application.register("dropdown", DropdownController);
